name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check for lint rule exclusions
        run: |
          # Check if lint.rules.exclude exists (excluding specific lint rules)
          if jq -e '.lint.rules.exclude' deno.json > /dev/null 2>&1; then
            echo "❌ Error: Lint rule exclusions (lint.rules.exclude) are not allowed in deno.json"
            echo "Found exclude in lint.rules configuration:"
            jq '.lint.rules' deno.json
            exit 1
          fi
          echo "✅ No lint rule exclusions found"

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run type checking
        run: deno check mod.ts

      - name: Run tests
        run: deno task test
